### ISSUE TITLE
Can i use it in c++? its giving errors

### ISSUE THREAD

**Issue by dolodi** [Spuckwaffel/DMALib#2]
unresolved external symbol

**Comment by Spuckwaffel** [comment]
awesome question with awesome information 
please use the .sln and use release and it should build with no issues

**Comment by dolodi** [comment]
Yeah thanks i was stupid, its all working great, but can it run on x86 ? it run perfectly on 64bit but i cant make it work on x86, are there any 32bit dll for memprocsfs?

**Comment by Spuckwaffel** [comment]
there's no reason for you to compile a x32 version if your device supports x64. But to answer your question, yes there are x86 files from memProc you have to use instead.
